### ISSUE TITLE
question for VBA code to get Card data form BEID after march 2014 #3

### ISSUE THREAD

**Issue by gerpat** [jdt/EID.Wrapper#8]
Hello,
Thanks a lot for your work and cooperation.
I have the same problem as JohanRVT.
I am working on a PC with windows 10 (X64) and office 2016 (X64).
When I am running the EID.Wrapper.Console, I get BirthDate, BirthPlace,FirstBames, Gender, Municipality, Nationality, NationalNumber, StreetAbdNumber, Surname, ZipCode but I don't get the card- and chip number, issuing municipality and validity begin- and end dates and the picture.

![captureeid](https://cloud.githubusercontent.com/assets/11030519/12033424/10b9a0f0-ae23-11e5-8250-634546d52e1a.JPG)

Using the EID.Wrapper.Register reference in Access 2016, 
Set data = wrapper.GetCardData()
If data.FirstCard Is Nothing Then
    MsgBox ("No valid card found!")
    MsgBox data.CardDataStatus
End If
When the ID card is not inserted, I get "No valid card found!", but when the ID card is inserted, I still get "No valid card found!" after a few seconds.
The data.CardDataStatus is 2.

I have downloaded your last EID.Wrapper-master and followed the instructions of README.md but it's still not working. The data.FisrtCard ist not available.
This is a big issue for me because I am in charge of the database of my club (more than 400 members). I have made a C# application that can read the EiD data and then export to the Access DB, but is not a proper way to work.
Many thanks in advance for your answer.

**Comment by JohanRVT** [comment]
I have no problem with the EID 32 bit Wrapper and Access 2007 also 32 bit. We don't use Access 2016, that is bagger.
Just that the cardreader sometimes only can read one card and than is the system not more responding but we think that that is a problem of the Citrix Server.

**Comment by gerpat** [comment]
Hello,
Thank you for your answer.
I have tried the 32 bit EID.Wrapper.Console but it's the same issue, I don't get all the info's mentioned in my previous comment.
BTW, I which you a Happy New Year!!

**Comment by jdt** [comment]
There are some important things to know about reading the data, and I'll have to edit the README to make that more obvious. 

First of all, there are two status fields: one on CardData and one on Card. CardData is simply a 'container' object that contains a list of all cards read with their data in Card-objects, and a status that indicates if all the cards were _read_ successfully. CardDataStatus 2 is for 'Ready' if I'm not mistaken, which simply means all card slots were read and the data is available for the wrapper to _parse_.

Secondly, after the cards are read and the data returned the data still has to be parsed from the cards. It can very well be that the data is read successfully but the wrapper could not convert some data. It might be corrupted, or it might be in some format that the wrapper doesn't know how to handle. Hence there is a list of Cards on CardData, and each card has its own status as well.

Now, FirstCard looks for the first card that was fully (and completely) parsed, and that's what your code does: you get a two-second delay because data is indeed read, but there is no card that was fully parsed. I'm guessing there is a problem in the wrapper somewhere.

As for the screenshot of the console utility: you got a partially filled object with some fields available. I would like to see the full output if possible, I think the Console should also output a CardStatus= and Error= line but I'm not seeing that in the output. Could you resize the console window so that everything fits onto the screen, blank out the private data and post the screenshot again? I'd like to see everything from the first line which should be something like 
_--------Kaart 0--------_
right up until the end which is
_Done... Press any key to exit_
I'm hoping that gives me an indication of where the wrapper is failing

**Comment by gerpat** [comment]
Thanks a lot for your answer.
I made a new screenshot  what we see is the full output. 
![captureger](https://cloud.githubusercontent.com/assets/11030519/12050204/c0bf1dd0-aef1-11e5-8ebf-210a302c6e04.JPG)

I get the same data of both console and the Register utilities. That means the missing data are the same as well.
Like you, I'm guessing about a problem in the wrapper.

**Comment by gerpat** [comment]
Thanks a lot for your answer.
I made a new screenshot  what we see is the full output. 
![captureger](https://cloud.githubusercontent.com/assets/11030519/12050204/c0bf1dd0-aef1-11e5-8ebf-210a302c6e04.JPG)

I get the same data of both console and the Register utilities. That means the missing data are the same as well.
Like you, I'm guessing about a problem in the wrapper.

**Comment by jdt** [comment]
Thanks for the additional information. I'll get a new version of the Wrapper out in the next few days to fix this issue and I'll get back to you on it.

**Comment by gerpat** [comment]
Thanks a lot for your quick answer.
I really appreciate your cooperation and I wish you a happy new year.
All the best for you and your family.
:smile:

**Comment by jdt** [comment]
I've put a new version of the wrapper up. If a field could not be parsed that field will now simply be ignored and left empty. There is a list of Warnings available on the carddata that can be used to find out more details.

I've tried the wrapper with a new card (one issued just last week) but could not find any issues so WHAT exactly causes this issue is still unknown to me. I'd appreciate it if you could again run the console and post an anonymized screenshot of the full console output. That should also show the warnings and give me the exact field that triggered the error. I hope to be able to dig through the documentation for that field and figure out what is wrong...

**Comment by gerpat** [comment]
You are the best!!
It's working fine to me, I get all the data I need on both console and the Register utilities. I've tested with my DB and all the fields are complete.
Many, many thanks to you!!
![captureger](https://cloud.githubusercontent.com/assets/11030519/12058095/79064192-af48-11e5-889f-f144517f900e.JPG)

**Comment by jdt** [comment]
Thanks for getting back to me on this. I can't find anything on those fields in the docs so I'll just leave this in _as is_, there will probably be situations where these fields are present and we want them available so I don't want to take them out completely either. The way this is handled now will be fine for either use so I'll leave that in.
