### ISSUE TITLE
Access to underlying eID Data

### ISSUE THREAD

**Issue by dalbre** [jdt/EID.Wrapper#9]
The com wrapper provides text input in human readable form, in the language in which the card was issued, i.e.
birthdate: 01 AOUT 1972
nationality: Allemagne (Rép.féd.) [in case of a foreigner's card ;-)]
etc...
How it is possible to access the "native" data stored on the card, i.e.:
birthdate: 19720801
nationality: DEU
etc.
This would help in making interpretation of the read data A LOT easier.

Many thanks

**Comment by jdt** [comment]
Actually, it is not a function of the wrapper. What you see is the native data returned from the EID. 

I'm guessing that there is a combination of laws and regulations at work here. The physical cards have the data on them localized to the place where they have been issued, so that the whole of the card is in Dutch, French or German. At some point somebody made the (arguably regrettable) decision that the electronic data should be in the same format as the data physically printed on the card. This makes sense from some practial and legal standpoints, but it puts the responsibility of doing the conversion on the developers of EID applications.

I'm assuming that during the drafting of the EID specifications a lot of lawyers were involved but nobody bothered to ask the software guys if it was all such a good idea...
